### ISSUE TITLE
Key is missing when using tailwind

### ISSUE THREAD

**Issue by njbmartin** [resend/react-email#1111] opened 2023-12-22 04:31 UTC
### Describe the Bug

Due to the way the tailwind component works, it renders an array of children, which requires a `key`.

So the key needs to be appended to the element like so (note the key would be the index of the `map`:

```tsx
export function appendKeyToValidElement(element: ReactNode, key: number): ReactNode {
  if (isValidElement(element) && element.key === null) {
    return cloneElement(element, { key });
  }
  return element;
}
```

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

https://github.com/resend/react-email

### To Reproduce

Start the demo and render the tailwind example. You will see the following warning in the console:

![image](https://github.com/resend/react-email/assets/5699471/42cf9bc5-ed41-4981-9bb4-1af51af44cce)

### Expected Behavior

React elements should rendered with a valid key.

**Comment by Code-Victor** [comment] 2024-01-05 23:47
I'm facing the same issue.
I have to reload the page every time to see the results

**Comment by nicitaacom** [comment] 2024-01-18 06:20
I'm see similar issue with `renderAsync`

**Comment by nicitaacom** [comment] 2024-01-19 01:50
I created minimal example of how to reproduce this issue - https://github.com/resend/react-email/issues/1150

And as I know this issue cause not `tailwind` package

It more related to `renderAsync` cause if you install oder version of `tailwind` this issue disappears and you got error about (APIs)[https://github.com/resend/react-email/issues/1140]

**Comment by ffiona** [comment] 2024-01-19 12:59
I didn't have this warning before I started using the `@react-email/tailwind` package. So for me as for the OP this issue was triggered by tailwind.

**Comment by gabrielmfern** [comment] 2024-01-22 13:33
For email templates the `key` prop is always going to be irrelevant, it doesn't matter the use case because things are not going to change, it is supposed to be static. The best path for this is not really to add a mocked key to certain components or elements, but maybe rather to silence the warning React logs.
I'll open a PR for this that will completely silence these warnings.

Maybe with something like https://github.com/facebook/react/issues/14374#issuecomment-461881546 or something like https://github.com/danneu/react-template-render/commit/8ae09d53a2ae879adcb4994689fed23086b8e254

**Comment by alnaranjo** [comment] 2024-02-22 21:59
Any updates on this? I also started seeing this when using @react-email/tailwind v0.0.14

**Comment by nicitaacom** [comment] 2024-02-23 07:26
Seems like in 1 month its hard to merge it

**Comment by basu-dev** [comment] 2024-02-23 16:16
> Any updates on this? I also started seeing this when using @react-email/tailwind v0.0.14

Me too on v0.0.14

**Comment by quangthien27** [comment] 2024-02-29 11:55
Having same issue with tailwind
`Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at body
    at XX (webpack-internal:///(api)/./lib/transactional/node_modules/@react-email/tailwind/dist/index.mjs:91400:25)
    at html
    at Html (webpack-internal:///(api)/./lib/transactional/node_modules/@react-email/html/dist/index.mjs:42:5)
`

**Comment by nicitaacom** [comment] 2024-03-01 08:25
@gabrielmfern please merge fix for this issue (that silence errors about "key is missing")

**Comment by nicitaacom** [comment] 2024-03-02 09:15
> For those interested, a solution that worked for me is posted here: [#1150 (comment)](https://github.com/resend/react-email/issues/1150#issuecomment-1973529988)

### Thank you - for me that work as well

**Comment by gabrielmfern** [comment] 2024-03-13 19:20
This should be fixed under the latest canary, `@react-email/tailwind@0.0.15-canary.1`. Let me know if anyone still experiences this issue due to the Tailwind component.

Release notes for it https://github.com/resend/react-email/releases/tag/%40react-email%2Ftailwind%400.0.15-canary.1.

**Closed by gabrielmfern** 2024-03-13 19:20 UTC
Labels: Type: Bug, Package: @react-email/tailwind
