### ISSUE TITLE
Error: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by ashemag** [resend/react-email#1295] opened 2024-02-09 06:19 UTC
### Describe the Bug

On trying to run the app in a new directory: 

Error: The "path" argument must be of type string. Received undefined

Source
src/actions/get-emails-directory-metadata.ts (69:38) @ path

  67 |
  68 | const emailFilenames = dirents
> 69 |   .filter((dirent) => isFileAnEmail(path.join(dirent.path, dirent.name)))
     |                                    ^
  70 |   .map((dirent) => dirent.name);
  71 |
  72 | const subDirectories = await Promise.all(

### Link to the code that reproduces this issue

just npx create-email@latest

### To Reproduce

npx create-email@latest
npm install 
npm run dev

### Expected Behavior

For the app to run

### What's your node version? (if relevant)

v18.13.0

**Comment by taychris** [comment] 2024-02-09 12:14
I encountered the same issue

**Comment by gabrielmfern** [comment] 2024-02-09 13:48
Closing as a duplicate of #1235.

**Closed by gabrielmfern** 2024-02-09 13:48 UTC
Labels: Type: Bug
