### ISSUE TITLE
`@react-email/tailwind` does not work with latest React 19 canary

### ISSUE THREAD

**Issue by ZipBrandon** [resend/react-email#1413] opened 2024-04-16 12:51 UTC
### Describe the Bug

`TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')` due to React 18.2 being compiled into the @react-email/tailwind. React 19 recently removed the access to `__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` which exists in the `@react-email/tailwind/dist/index.mjs` via the `react-jsx-runtime.production.min.js` code.

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

https://github.com/ZipBrandon/react-email-troubleshoot

### To Reproduce

Modify your package.json to include the latest React canary with specified overrides.
```
"dependencies": {
...
    "react": "19.0.0-canary-96c584661-20240412",
    "react-dom": "19.0.0-canary-96c584661-20240412",
...
},
"overrides": {
    "react": "19.0.0-canary-96c584661-20240412",
    "react-dom": "19.0.0-canary-96c584661-20240412"
  }
```

### Expected Behavior

Not to throw a TypeError

**Comment by gabrielmfern** [comment] 2024-04-16 12:54
What would be the issue with React Email running on a different React version than the one you are using? Just wondering because you added in the override, so that forces React Email into using the React you are using.

**Comment by gabrielmfern** [comment] 2024-04-16 13:10
@ZipBrandon Just asking due to curiosity, this certainly is a bug, and I'll look into fixing it. We should not be bundling in anything from React. Thank you so much for opening this issue! :)

**Comment by gabrielmfern** [comment] 2024-05-15 14:33
A fix for this was released under [`@react-email/tailwind@0.0.17-canary.0`](https://github.com/resend/react-email/releases/tag/%40react-email%2Ftailwind%400.0.17-canary.0)!

**Comment by viczam** [comment] 2024-05-15 16:54
I get this error after the alpha updates: `renderToStream is not a function`

```json
"@react-email/components": "^0.0.18-canary.0",
"@react-email/render": "^0.0.14-canary.0",
"@react-email/tailwind": "0.0.17-canary.0",
"next": "14.3.0-canary.61",
```

**Comment by gabrielmfern** [comment] 2024-05-16 17:35
@viczam Thanks for letting me know about this! Weirdly enough, we don't call that function at all, can you show the full stack trace? I'll also try making a reproduction of it myself

**Comment by gabrielmfern** [comment] 2024-05-21 13:37
This has been fixed and released under [`@react-email/tailwind@0.0.17`](https://github.com/resend/react-email/releases/tag/%40react-email%2Ftailwind%400.0.17). If anyone still experiences this issue, please let me know and I'll reopen this issue.

**Closed by gabrielmfern** 2024-05-21 13:37 UTC
Labels: Type: Bug, Package: @react-email/tailwind, Fixed under canary

**Comment by khuezy** [comment] 2024-07-24 17:43
Hi @gabrielmfern I have the same error using `@react-email/render`. Is the fix similar?

**Comment by theonlydaleking** [comment] 2024-08-24 07:57
For anyone else reading this - something that worked for me while I was trialing nextjs 15RC was to remove the `.react-email ` folder after: 
`pnpm up next@rc react@rc react-dom@rc react-email@latest @react-email/components@latest`

then build would work
