### ISSUE TITLE
Bun runtime fails react-mail@>2.0.0 - defaults to it without warning when node isn't installed

### ISSUE THREAD

**Issue by codeScourge** [resend/react-email#1429] opened 2024-04-25 06:04 UTC
### Describe the Bug

I recently had an issue with React-Mail closing without any error when running with bun (installed on WSL), see reproduction here: https://github.com/codeScourge/react-email. I was able to workaround by downgrading to react-mail@1.9.0

The error seemed to be fixed by installing Node in WSL, as proposed by gabrielmfern:

>I think I've figured it out. When running on WSL you might have not installed Node at all, in that case, it seems like it fails the same you mentioned. It also fails the same way when running with bun --bun dev while having Node installed. So it seems like bun falls back to running with its runtime if Node isn't installed, so basically it runs bun --bun dev. Haven't checked on their code and I couldn't find anything related to this on their docs.

### Link to the code that reproduces this issue

https://github.com/codeScourge/react-email

### To Reproduce

https://github.com/codeScourge/react-email, see ReadME

### Expected Behavior

it should start a dev server

**Comment by atomicpages** [comment] 2024-06-03 01:29
Bun doesn't contain all the dependencies required to run next. For example: `bun -b email dev` 
 and `bun -b email build` relies on `TextDecoderStream` which isn't supported in bun yet

**Comment by gabrielmfern** [comment] 2024-08-02 18:26
Thinking a bit more about this, this isn't exactly an issue on our side. The behavior of Bun defaulting to itself is mostly fine, but the regarding about what the problem is here is that Bun does not support to be used as a runtime for React Email at all.

Sorry for the confusion in asking for you to open this, closing it as not planned for now.

**Closed by gabrielmfern** 2024-08-02 18:26 UTC
Labels: Type: Bug, Package: react-email
