### ISSUE TITLE
Outlook does not respect styling

### ISSUE THREAD

**Issue by dreinon** [resend/react-email#480] opened 2023-02-16 18:27 UTC
Hi!
I have read #159 but not only outlook does not respect this, but also paddings and font weight. We are using the Tailwind component (even adding it to each custom component).
Any ideas on how to address this issue would me much appreciated.

Thanks!

**Comment by bukinoshita** [comment] 2023-03-03 07:57
Can you share the code?

**Comment by joshgdale** [comment] 2023-03-20 17:58
I've noticed issues is width of Sections... using the tailwind class `w-[600px]` for example works great in browser & Apple Mail, but doesn't work in Outlook. This seems to be because along with applying the 600px class, it also applies a `width="100%"` attribute to the resulting table. Outlook seems to not respect the `style="width: 600px"` and only applies the width attribute. This is possibly part of a larger issue though as Outlook's rendering engine is different from everything else for now.

**Comment by dreinon** [comment] 2023-06-27 22:57
Hi! Our problem is the one @arpi0003 mentions. Any news? Thanks!

**Comment by erik06** [comment] 2023-10-17 19:55
I can confirm that tailwind styling that outputs to rem sizing does not work in Outlook on Windows but converting all rem values to px values fixes the issues mostly

**Comment by merttyilmaz** [comment] 2024-08-08 00:07
Hey guys, currently I'm running into this issue. I will share my code and tailwind config and the images here as well. Please give me your feedback. 

`import * as React from "react";
import {
  Html,
  Head,
  Font,
  Tailwind,
  Container,
  Section,
  Img,
  Text,
  Body,
  Row,
  Column,
  Button,
} from "@react-email/components";

export default function Email() {
  return (
    <Html>
      <Tailwind>
        <Head>
          <Font
            fontFamily="Inter"
            fallbackFontFamily="sans-serif"
            webFont={{
              url: "https://rsms.me/inter/inter.css",
              format: "truetype",
            }}
          />
          <title>Cancel Subscription</title>
        </Head>
        <Body className="mx-auto bg-[#F4F5F6]">
          <Container className="my-6 text-xs">
            <Img
              src="https://www.qrispy.com/qrispy-logo.png/"
              alt="logo"
              className="h-[46px] w-[102px]"
            />
            <Section className="mt-[18px] rounded-2xl border border-[#EAEBED] bg-white p-6 sm:w-[600px]">
              <Row className="mb-4">
                <Text className="text-center text-[22px] font-semibold text-black">
                  Sorry to see you go.
                </Text>
              </Row>
              <Row className="mb-4">
                <Text className="text-sm text-black">
                  Your Qrispy membership has been cancelled. You&apos;ll still
                  have your membership benefits until the end of your current
                  billing cycle on <strong>April 27th, 2022.</strong>
                </Text>
              </Row>
              <Row className="mb-4">
                <Text className="text-sm text-black">
                  You may not be a member anymore, but you are still part of
                  Qrispy.
                </Text>
              </Row>
              <Row className="mb-4">
                <Text className="text-sm text-black">
                  Thanks,
                  <br /> The Qrispy Team
                </Text>
              </Row>
              <Row>
                <Img
                  src="https://www.qrispy.com/cancel-leaflet.png/"
                  alt="logo"
                  className="h-[111px] w-[552px]"
                />
              </Row>
              <Section className="mt-5 rounded-lg bg-[#3D4A7A0D] px-4">
                <Row className="mb-4">
                  <Text className="text-sm text-black">
                    When your paid subscription ends, your call and SMS
                    permissions will be reset. If you cancel during the free
                    trial, these permissions will reset immediately.
                  </Text>
                </Row>
                <Row className="mb-4">
                  <Text className="text-sm text-black">
                    From the subscription end or cancellation date, we will
                    retain your number for 45 days. During this time, you can
                    renew your subscription via the &quot;Renew
                    Subscription&quot; button under Subscription Management.
                  </Text>
                </Row>
                <Row className="mb-4">
                  <Text className="text-sm text-black">
                    If you do not renew within 45 days, your number will be
                    removed and returned to the pool. You can still log in, but
                    you won&apos;t have an assigned number.
                  </Text>
                </Row>
              </Section>
            </Section>
          </Container>
        </Body>
      </Tailwind>
    </Html>
  );
}
`

`import type { TailwindConfig } from "@react-email/tailwind";

export default {
  theme: {
    fontSize: {
      xs: ["12px", { lineHeight: "16px" }],
      sm: ["14px", { lineHeight: "20px" }],
      base: ["16px", { lineHeight: "24px" }],
      lg: ["18px", { lineHeight: "28px" }],
      xl: ["20px", { lineHeight: "28px" }],
      "2xl": ["24px", { lineHeight: "32px" }],
      "3xl": ["30px", { lineHeight: "36px" }],
      "4xl": ["36px", { lineHeight: "36px" }],
      "5xl": ["48px", { lineHeight: "1" }],
      "6xl": ["60px", { lineHeight: "1" }],
      "7xl": ["72px", { lineHeight: "1" }],
      "8xl": ["96px", { lineHeight: "1" }],
      "9xl": ["144px", { lineHeight: "1" }],
    },
    spacing: {
      px: "1px",
      0: "0",
      0.5: "2px",
      1: "4px",
      1.5: "6px",
      2: "8px",
      2.5: "10px",
      3: "12px",
      3.5: "14px",
      4: "16px",
      5: "20px",
      6: "24px",
      7: "28px",
      8: "32px",
      9: "36px",
      10: "40px",
      11: "44px",
      12: "48px",
      14: "56px",
      16: "64px",
      20: "80px",
      24: "96px",
      28: "112px",
      32: "128px",
      36: "144px",
      40: "160px",
      44: "176px",
      48: "192px",
      52: "208px",
      56: "224px",
      60: "240px",
      64: "256px",
      72: "288px",
      80: "320px",
      96: "384px",
    },
  },
} satisfies TailwindConfig;
`
This is my folder structure(I'm using it in an existing project and its tailwind config shouldnt interfere with the actual projects tailwind config):
![image](https://github.com/user-attachments/assets/15dfa5d8-7f2c-4c55-8dd7-4eb5c1d1722e)

The email for Gmail mobile and web and also Apple mail : 
![image](https://github.com/user-attachments/assets/2208a7af-c745-40f6-ab6d-7bad9a5b2c0d)
The email for **Outlook Desktop App** : 
![image](https://github.com/user-attachments/assets/bfa87c44-213b-4947-b9a3-62ee48305bfb)

**Comment by gabrielmfern** [comment] 2024-11-19 14:11
This issue seems very general with the comments, so I am going to close as not planned for now. Anyone that still experiences any of the mentioned problems should open an issue for your specific problem so that it can be addressed easily.

The original comment mentions rounded corners, and for us to completely support that on Outlook we would need to use VML, so it might not be feasible at all. As for the other problems with padding, they have already been fixed as of latest versions.

**Closed by gabrielmfern** 2024-11-19 14:11 UTC
Labels: Client: Outlook, Resolution: Needs More Information
