### ISSUE TITLE
App router email preview not importing email properly

### ISSUE THREAD

**Issue by Coderman562** [resend/react-email#876] opened 2023-08-05 16:48 UTC
### Describe the Bug

import issue when importing email

./src/app/preview/[slug]/page.tsx:26:23
Module not found: Can't resolve '../../../../emails'
  24 |   });
  25 | 
> 26 |   const Email = (await import(`../../../../emails/${params.slug}`)).default;
     |                       ^
  27 |   const markup = render(<Email />, { pretty: true });
  28 |   const plainText = render(<Email />, { plainText: true });
  29 |   const basePath = pathJoin(process.cwd(), CONTENT_DIR);

https://nextjs.org/docs/messages/module-not-found

### Link to the code that reproduces this issue

https://github.com/Coderman562/react-email-starter

### To Reproduce

npx create-email@latest

cd react-email-starter

npm install

npm run dev

### Expected Behavior

should import the react email code properly and display on page, instead gives error

### What's your node version? (if relevant)

v18.16.1

**Comment by lordelogos** [comment] 2023-08-12 01:18
Hey @Coderman562,

I just try to reproduce this and the setup works fine.
Here is a video of me going through the setup process from scratch with the steps to reproduce
(Maybe try using Yarn)

Link: https://youtu.be/Xg7zUt9ToP0

**Comment by alper-guven** [comment] 2023-08-12 15:42
The PR #869 fixes this issue. I also have a similar fix for this issue but i liked #869  better, so won't create a PR.

I have a suggestion, though.
- Install `react-email@1.9.3` using [automated setup](https://react.email/docs/getting-started/automatic-setup).
- Apply the PR into auto generated NextJS app that has been created when you first run `email dev` command.
- Track the generated app with Git. Don't forget to add `.next` & `node_modules` to `.gitignore`

This way, you can atleast use the project without the wait.

NOTE: This version (`react-email@1.9.3`) has another problem on its `email dev` script. Main process rejects to exit on `SIGINT` signal since it can not gracefully shutdown. It can't kill the sub process and rejects to exit main process.

**Comment by lordelogos** [comment] 2023-08-12 16:56
@alper-guven what error are you referring to?

I have followed the steps to reproduce and the setup works fine.

**Comment by alper-guven** [comment] 2023-08-12 18:02
I followed the same steps and I was able to reproduce the error.


![react-email--error](https://github.com/resendlabs/react-email/assets/10487846/523c7a72-d35b-4fc9-ae7a-e6f828333766)

I marked the parts which causes this error + additional errors.


![react-email--fix](https://github.com/resendlabs/react-email/assets/10487846/a0650ef1-2812-4103-9a28-b7e712d9adee)

If you check the commits from the PR #869 you can see that the PR changes the parts I marked.

**Comment by nojuskybartas** [comment] 2023-08-23 07:57
> The PR #869 fixes this issue. I also have a similar fix for this issue but i liked #869 better, so won't create a PR.
> 
> I have a suggestion, though.
> 
> * Install `react-email@1.9.3` using [automated setup](https://react.email/docs/getting-started/automatic-setup).
> * Apply the PR into auto generated NextJS app that has been created when you first run `email dev` command.
> * Track the generated app with Git. Don't forget to add `.next` & `node_modules` to `.gitignore`
> 
> This way, you can atleast use the project without the wait.

Followed the steps, though the import error persists, I seem to _have_ to move the `emails` folder into the auto-generated `.react-email` folder manually for it to work. Is this by design, or a bug?

(I'm using npm, when using yarn the next server didn't start at all)

**Comment by gabrielmfern** [comment] 2024-01-23 13:29
This should not happen with the new version for the CLI `react-email@2.0.0` as it doesn't use this import hack anymore.

**Closed by gabrielmfern** 2024-01-23 13:29 UTC
Labels: Type: Bug
