### ISSUE TITLE
<Heading /> not rendered inside <Tailwind />

### ISSUE THREAD

**Issue by Noventhree** [resend/react-email#1405] opened 2024-04-08 09:38 UTC
### Describe the Bug

```import { Html, Button, Body, Heading, Tailwind } from '@react-email/components';

const Example = () => (
  <Html>
    <Tailwind>
      <Body>
          <Heading >test heading</Heading>
          <Button>test button</Button>
      </Body>
    </Tailwind>
  </Html>
);

export default Example;
```

doesn't render heading 

```import { Html, Button, Body, Heading } from '@react-email/components';

const Example = () => (
  <Html>
      <Body>
          <Heading >test heading</Heading>
          <Button>test button</Button>
      </Body>
  </Html>
);

export default Example;
```
does render heading. spotted after latest version bump

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

in description

### To Reproduce

copy paste code in description

### Expected Behavior

heading can be rendered inside tailwind

**Comment by gabrielmfern** [comment] 2024-04-08 09:50
Closing as a duplicate of #1391.

It should be working under `@react-email/tailwind 0.0.16-canary.1`.

**Closed by gabrielmfern** 2024-04-08 09:50 UTC
Labels: Type: Bug
