### ISSUE TITLE
Unexpected, unredable characters in generated HTML

### ISSUE THREAD

**Issue by UNOwen** [resend/react-email#1667] opened 2024-09-09 20:06 UTC
### Describe the Bug

When rendering HTML using react-email 3.0.1, I randomly observe unprintable characters rendered in between or instead of the non-latin letters of the email text, no more than 1-2 occurrences per email typically. The issue seems semi-random, dependent on the amount of react markup and text before the affected character, and also dependent on the execution environment (locally rendered preview and server-side cloudflare worker insert these "broken" characters at different parts of the rendered HTML).

Example:

```
<Text className="text-zinc-600 dark:text-zinc-300 leading-6">
        Поздравляю! Вы завершили офлайн-курс по улучшению речи и литературному мастерству Litcondit. 
        Если вам понравились занятия и вы заинтересованы в том, чтобы научиться виртуозно говорить и писать, 
        а еще разбираться в литературе, приходите на занятия:
</Text>
```

Result:

```
Поздравляю! Вы завершили офлайн-курс по улучшению речи и литерату�рному мастерству Litcondit. 
Если вам понравились занятия и вы заинтересованы в том, чтобы научиться виртуозно говорить и писать, 
а еще разбираться в литературе, приходите на занятия:
```

(note the `�` character)

```
        "@react-email/components": "^0.0.24",
        "@react-email/preview": "0.0.11",
        "react-email": "3.0.1",
```

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://github.com/UNOwen/litcondit-worker

### To Reproduce

Have the below snippet repeated multiple times:

```
<Text className="text-zinc-600 dark:text-zinc-300 leading-6">
        Поздравляю! Вы завершили офлайн-курс по улучшению речи и литературному мастерству Litcondit. 
        Если вам понравились занятия и вы заинтересованы в том, чтобы научиться виртуозно говорить и писать, 
        а еще разбираться в литературе, приходите на занятия:
</Text>
```

Preview the dev version of emails or render in production. Observe broke characters in the email.

### Expected Behavior

No unprintable characters in the email.

**Comment by blnvdanil** [comment] 2024-09-10 10:40
We have also encountered this bug, it occures randomly, any change to the JSX layout or styles may lead to appearing/disappearing of these characters, it seems to be a \0 character

**Comment by gabrielmfern** [comment] 2024-09-11 14:34
The code to the reproduction seems to be down, can you make it public?

**Comment by UNOwen** [comment] 2024-09-13 18:30
> The code to the reproduction seems to be down, can you make it public?

Gabriel, I’d like to keep the repository private, but I granted you access.

**Comment by UNOwen** [comment] 2024-09-14 12:54
Upon some basic investigation, the character involved has hex byes of EF BF BD, and is the https://www.cogsci.ed.ac.uk/~richard/utf-8.cgi?input=%EF%BF%BD&mode=char "REPLACEMENT CHARACTER". It repeats twice in a row a lot of the time. It overwrites the contents of the email rather than inserting itself in between letters. E.g. hex bytes D0 BF for letter "п" were replaced with EF BF BD EF BF BD.

**Comment by KevinGregull** [comment] 2024-09-18 18:48
We see the same issue occuring. For us it happens on the "€" Character. I am quite certain that this is not an input encoding problem but rather something that occurs during the rendering of the HTML. Because we do display the € sign in Order Line-Items which are rendered in a loop. Sometimes a single of the looped € Characters is being replaced by the aformentioned �� characters, while the others render fine. It also happens with Umlauts sometimes "äöü". I've never seen it occur in any standard ASCII Character, thus far.

**Comment by gabrielmfern** [comment] 2024-09-26 15:16
@KevinGregull @UNOwen What other things about the environment you are using to render can you share (OS, rendering in the browser, in Node, what browser)?

**Comment by UNOwen** [comment] 2024-09-26 15:26
The issue seems to be universal. I am observing these characters appearing both when rending emails within Cloudflare workers, and while on my macOS desktop in preview mode in the browser.

**Comment by gabrielmfern** [comment] 2024-09-26 15:30
Asking this because I'm really not getting any null characters on my side, and I'm running things on Linux with the same email template. It might be something related to Mac in general because the preview server does not call render in the browser

**Comment by blnvdanil** [comment] 2024-09-26 15:42
In my case, I run it on Arch Linux, and still have the same problem

**Comment by gabrielmfern** [comment] 2024-09-26 16:15
Got a reproduction of it, but not in the preview server — only when rendering directly with JavaScript in the browser.

**Comment by KevinGregull** [comment] 2024-09-26 17:12
I am rendering it as a cli application. It's running in the bun docker Container oven/bun.

**Comment by gabrielmfern** [comment] 2024-09-26 17:52
Released a fix that worked on my reproduction. Could you all test with `@react-email/components@0.0.26-canary.3` or `@react-email/render@1.0.2-canary.0`?

**Comment by UNOwen** [comment] 2024-09-27 15:03
With these component versions installed, the email appears to be completely blank when rendered on a cloudflare worker and displayed in browse or email client like Mail. The HTML seems to be in place, but there is some javascript which gets appended and removing the content upon render. Text version of the email is not affected. 

[demo.html.zip](https://github.com/user-attachments/files/17166085/demo.html.zip)

**Comment by UNOwen** [comment] 2024-09-27 18:50
I am using `"react-email": "3.0.1"` to set rendering up overall, and using `import { render } from '@react-email/components'` method. Rendering worked before updating the dependencies, and I haven't done any changes outside of updating the two dependencies you mentioned. The repository is linked in the bugreport.

**Comment by UNOwen** [comment] 2024-09-28 16:31
Upon upgrading `react-email` to `3.0.2-canary.2` on the whole, I am still observing "empty" HTML emails upon delivering to the email inbox. Browser preview in the dev server looks fine.

**Comment by grigmag** [comment] 2024-10-30 11:18
Hi, I'm also experiencing the same problem using the greek language, even in the `3.0.2-canary.2` version. 

See my minimal reproduction here (make sure you are in the correct branch, which is not the main branch):
https://github.com/grigmag/react-email-unreadable-characters-bug/tree/unreadable-characters-bug

The produced output in the dev server (`pnpm dev`) after a large amount of repetions of the text "Αβγδεζηθικλμνξοπρστυφχψω" becomes "Αβγδεζηθικλμνξοπρστυφ�χψω".

When sending the test email, I do not see the `�` character in my gmail, so the bug does not seem to affect the sent emails for me.

**Comment by gabrielmfern** [comment] 2024-11-13 15:52
Closing as the original issue here was fixed. 

As for the problem @grigmag mentioned above, it is an underlying issue in React DOM that shouldn't really cause any problems in normal circumstances, as workaround we are simply not going to render null byte characters in the preview server for now. The null byte character also seems to go away with React 19.

**Closed by gabrielmfern** 2024-11-13 15:52 UTC
Labels: Type: Bug, Package: @react-email/render
