### ISSUE TITLE
Heading component is missing when you use Tailwind

### ISSUE THREAD

**Issue by jxh0414com** [resend/react-email#1404] opened 2024-04-08 05:00 UTC
### Describe the Bug

When you wrap Body with Tailwind whenever I use Heading inside the body, its not showing up in the 'email dev', if i remove the tailwind, the Heading component show back up? Any fix or am i doing it wrong somehow?

Also how do reset all the component's css? like Text has margin i want to reset them.

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

none

### To Reproduce

    <Html>
      <Head />
      <Preview>{previewText}</Preview>
      <Tailwind>
        <Body className="bg-white my-auto mx-auto font-sans px-2">
          <Heading className="text-black text-[24px] font-normal text-center p-0 my-[30px] mx-0">
            Join <strong>{teamName}</strong> on <strong>Vercel</strong>
          </Heading>
        </Body>
      </Tailwind>
    </Html>

### Expected Behavior

you should see  Join <strong>{teamName}</strong> on <strong>Vercel  on the screen but none show up
![1712552402964](https://github.com/resend/react-email/assets/46506357/ee58f189-cbd6-4b65-a776-524210db15cc)

**Comment by gabrielmfern** [comment] 2024-04-08 09:02
Closing as a duplicate of #1391.

It should be working under `@react-email/tailwind 0.0.16-canary.1`.

**Closed by gabrielmfern** 2024-04-08 09:02 UTC
Labels: Type: Bug
