### ISSUE TITLE
Markdown component error "value.includes is not a function" after updating to latest version

### ISSUE THREAD

**Issue by Hainesy** [resend/react-email#1416] opened 2024-04-19 13:35 UTC
### Describe the Bug

After upgrading from version `0.0.15` to `0.0.16` of `@react-email/components`, I now get this error thrown from the `Markdown` component. 

<img width="982" alt="image" src="https://github.com/resend/react-email/assets/520883/f8145387-5858-4c1f-94d2-1e7730805f3e">

### Which package is affected (leave empty if unsure)

@react-email/components

### Link to the code that reproduces this issue

N/A

### To Reproduce

For me, simply using the `ReactEmailMarkdown` component with version 0.0.16 caused the problem.

### Expected Behavior

Not throw an error.

**Comment by gabrielmfern** [comment] 2024-04-19 13:42
I think this might be fixed on canary, can you try `@react-email/components@0.0.17-canary.1`?

**Comment by gabrielmfern** [comment] 2024-07-26 22:07
Closing this as stale. If the issue is still present, let me know with a reproduction and I'll reopen.

**Closed by gabrielmfern** 2024-07-26 22:07 UTC
Labels: Type: Bug
