### ISSUE TITLE
Module not found: Can't resolve './lib/beautify'

### ISSUE THREAD

**Issue by theDanielJLewis** [resend/react-email#730] opened 2023-06-27 17:46 UTC
### Describe the Bug

When importing my exported email template into a .ts file for sending, Next.js 13.4 returns the error "Module not found: Can't resolve './lib/beautify'."

Here's that .ts file's code:

```js
import { NewItemEmail } from '../../../react-email-starter/out/new-item';
import { render } from '@react-email/render';

import formData from 'form-data';
import Mailgun, { MailgunClientOptions, MessagesSendResult } from 'mailgun.js';
const mailgun = new Mailgun(formData);
const mg = mailgun.client({
	username: 'api',
	key: process.env.MAILGUN_API_KEY || '',
});

export async function sendNewItemEmail(item, user) {
	const emailHtml = render(NewItemEmail({ item, user }));
	const messageData = {
		from: '…',
		to: '…',
		subject: `Added: ${item.title}`,
		html: emailHtml,
	};
	try {
		const result = await mg.messages.create(
			process.env.MAILGUN_DOMAIN!,
			messageData
		);
		console.log(result);
	} catch (error) {
		if (error) console.error(error);
	}
}
```

### Which package is affected (leave empty if unsure)

@react-email/render

### Link to the code that reproduces this issue

n/a

### To Reproduce

1. Create email
2. Export
3. Import into function
4. Run app

### Expected Behavior

I expect it to _not_ give an error.

### What's your node version? (if relevant)

18.15.0

**Comment by TheXienator** [comment] 2023-08-30 23:34
Also am having this issue when I have a types folder that I am importing to import some shared Props that would be use across emails. It seems when I do the import like this:
```
import { InviteUserProps, defaultInviteUserProps } from "./types/invite-user.js"
```

There is an error, but when I remove the `.js` it does seem to work:
```
import { InviteUserProps, defaultInviteUserProps } from "./types/invite-user"
```

I also noticed in some of the examples the `.js` is not included in the imports: https://github.com/lordelogos/react-email-postmark/blob/master/src/index.js#L2

However I do need the `.js` in because it thinks it is a module if I just try to import it without the .js

**Comment by wardxela** [comment] 2023-09-15 20:37
I got the same issue in my turbo repo when i decided to move my emails to a separate package.

**Comment by gabrielmfern** [comment] 2024-03-27 12:45
Since there is no reproduction repo here, and assuming that this is an ESM compatibility issue with the import for js-beautify, this does seem to work for the latest version of `@react-email/render`.

Will close this one as completed for now, if anyone still experiences this issue, please provide a reproduction, and then I'll reopen this.

**Closed by gabrielmfern** 2024-03-27 12:45 UTC
Labels: Type: Bug, Package: @react-email/render
