### ISSUE TITLE
Couldn't find any `pages` or `app` directory. Please create one under the project root

### ISSUE THREAD

**Issue by MrDalo** [resend/react-email#1308] opened 2024-02-13 15:12 UTC
### Describe the Bug

Hi! I want to use React-email with my Nextjs 14 project but I am always getting error "Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root"

So I tried manual and then automatic installation with brand new project with `npx create-email@latest` but same story, still getting this error:
`npm run dev

> emails@0.0.18 dev
> email dev

    React Email 2.0.0
    Running preview at:          http://localhost:3000

  ⠙ Getting react-email preview server ready...
Error: > Couldn't find any \`pages\` or \`app\` directory. Please create one under the project root
    at findPagesDir (C:\Users\dadok\Desktop\Doma IT\API project\react-email\react-email-starter\node_modules\next\dist\lib\find-pages-dir.js:42:15)    
    at initialize (C:\Users\dadok\Desktop\Doma IT\API project\react-email\react-email-starter\node_modules\next\dist\server\lib\router-server.js:71:69)    at async NextCustomServer.prepare (C:\Users\dadok\Desktop\Doma IT\API project\react-email\react-email-starter\node_modules\next\dist\server\next.js:240:28)

shutting down dev server`

Can you help me with that please?

### Link to the code that reproduces this issue

.

### To Reproduce

.

### Expected Behavior

.

### What's your node version? (if relevant)

20.9.0

**Comment by gabrielmfern** [comment] 2024-02-13 15:13
Closing as a duplicate of #1225.

This also has already been fixed and release as of `react-email@2.1.0-canary.1` try out. Stable release soon as well!

**Closed by gabrielmfern** 2024-02-13 15:13 UTC
Labels: Type: Bug

**Comment by JuanSpada** [comment] 2024-02-15 14:16
@gabrielmfern how can I install react-email@2.1.0-canary.1 ? 

Thank you
