### ISSUE TITLE
Couldn't find any `pages` or `app` directory. Please create one under the project root

### ISSUE THREAD

**Issue by dvsmc** [resend/react-email#1252] opened 2024-01-26 00:58 UTC
### Describe the Bug

When creating new react-email project, this error appears when running `email dev`:

```
PS E:\react-email-starter> yarn dev
yarn run v1.22.19
$ email dev
    React Email 2.0.0
    Running preview at:          http://localhost:3000

  \ Getting react-email preview server ready...
Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
    at findPagesDir (E:\react-email-starter\node_modules\next\dist\lib\find-pages-dir.js:42:15)
    at initialize (E:\react-email-starter\node_modules\next\dist\server\lib\router-server.js:71:69)
    at async NextCustomServer.prepare (E:\react-email-starter\node_modules\next\dist\server\next.js:240:28)

shutting down dev server
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

![image](https://github.com/resend/react-email/assets/112554734/b9af2fb4-1b49-41ed-89be-de6433c14481)

Windows 10 Pro, 64bit, node v21.4.0, npm /npx v9.8.1, yarn v1.22.19

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

No code, use commands from docs guide

### To Reproduce

`npx create-email@latest`

`cd react-email-starter`

`yarn install`

`yarn dev`

*shows error*

### Expected Behavior

No errors, should open browser with email templates.

### What's your node version? (if relevant)

21.4.0

**Comment by gabrielmfern** [comment] 2024-01-26 01:02
Closing as a duplicate of #1225

**Closed by gabrielmfern** 2024-01-26 01:02 UTC
Labels: Type: Bug

**Comment by dvsmc** [comment] 2024-01-26 01:06
Ahh thanks, tried to search and couldn't find existing issue!

**Comment by gabrielmfern** [comment] 2024-01-26 01:47
@dvsmc Np! Getting it merged for you guys soon as well!
