### ISSUE TITLE
`js-beautify` esm issue when using `@react-email/render`

### ISSUE THREAD

**Issue by jd-carroll** [resend/react-email#1147] opened 2024-01-17 02:20 UTC
### Describe the Bug

I just ran the automated setup `npx create-email@latest` and am receiving the following error in the console:

```
➤ YN0000: └ Completed in 2s 902ms
✔ Dependencies installed
   ▲ Next.js 14.0.3
   - Local:        http://localhost:3000
   - Experiments (use at your own risk):
     · externalDir

 ✓ Ready in 757ms
 ○ Compiling / ...
 ✓ Compiled / in 3.7s (1315 modules)
 ✓ Compiled in 221ms (657 modules)
 ✓ Compiled /preview/[slug] in 351ms (1335 modules)

 ⨯ import { html } from "js-beautify";
         ^^^^
SyntaxError: Named export 'html' not found. The requested module 'js-beautify' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'js-beautify';
const { html } = pkg;
```

### Link to the code that reproduces this issue

NA

### To Reproduce

1) `npx create-email@latest`
2) `yarn install`
3) `yarn dev`
4) Click on a demo email

### Expected Behavior

Not to error out

### What's your node version? (if relevant)

v20

**Comment by jd-carroll** [comment] 2024-01-17 04:35
I had to go in an manually change all the versions **to anything not released in the last 24hrs** and it all started working.

But as an outsider (**who is really excited to use this project**) the versioning seems to be a mess. There have been over 20 releases in the past week and now there also seems to be a v2 release available. And some things have a `0.*` as their major so every minor release is a breaking release but yet other projects are moving on to a v2 major release. 

I also cannot make heads or tails of which branch is what (should I be focused on canary or main to start learning this project).

Again, criticism with ❤️, would love to see this project succeed (and then become a customer of Resend 🙃 )

**Comment by lunoob** [comment] 2024-01-17 05:10
<img width="874" alt="image" src="https://github.com/resend/react-email/assets/49156607/fce1cb0f-f315-4bef-a0a5-bae19f744432">

some issue

**Comment by gabrielmfern** [comment] 2024-01-17 06:54
This shouldn't be caused by the latest version per se, it's an esm and cjs compatibility issue that we already have a PR for #1128.

**Comment by gabrielmfern** [comment] 2024-01-17 06:55
@jd-carroll 
> I had to go in an manually change all the versions **to anything not released in the last 24hrs** and it all started working.

What other packages had issues for you? I'll look into it.

**Comment by sergical** [comment] 2024-01-17 16:26
+1 just ran into the same issue
```
{
  "name": "emails",
  "version": "0.0.18",
  "private": true,
  "workspaces": [
    ".react-email"
  ],
  "scripts": {
    "dev": "email dev",
    "export": "email export"
  },
  "dependencies": {
    "@react-email/components": "0.0.13",
    "react-email": "1.10.1"
  }
}
```

```
node --version
v18.17.0
```

**Comment by iansamz** [comment] 2024-01-18 08:21
+1 just ran into the same issue

**Comment by iansamz** [comment] 2024-01-18 08:36
I had to use version `[2.0.0-canary.4](https://www.npmjs.com/package/react-email/v/2.0.0-canary.4)` to get it working.

**Comment by gjunkie** [comment] 2024-01-18 22:53
Also seeing this issue.

node v21.1.0

**Comment by gjunkie** [comment] 2024-01-18 23:42
In case this helps anyone, I'm using NextJS 14 and was able to get it working by using `transpilePackages` in `next.config.js`.

```
const nextConfig = {
  transpilePackages: [
    "js-beautify",
    "@react-email/components",
    "@react-email/render",
  ],
};

module.exports = nextConfig;
```

**Comment by Qodestackr** [comment] 2024-01-19 08:45
+1 Getting the same bug :smile:

**Comment by Qodestackr** [comment] 2024-01-19 08:47
> In case this helps anyone, I'm using NextJS 14 and was able to get it working by using `transpilePackages` in `next.config.js`.
> 
> ```
> const nextConfig = {
>   transpilePackages: [
>     "js-beautify",
>     "@react-email/components",
>     "@react-email/render",
>   ],
> };
> 
> module.exports = nextConfig;
> ```

Interesting but got no fix..Using Nextjs `12.3.1`. Will be forced to migrate if this is the fix

**Comment by edbella** [comment] 2024-01-19 10:01
I'm completely blocked here using Remix 2.5.1. No way forward. Does anyone have suggestions?

**Comment by gabrielmfern** [comment] 2024-01-19 12:27
This has now been fixed with `@react-email/render@0.0.12` everyone!
If anyone still has this issue lmk.

**Closed by gabrielmfern** 2024-01-19 12:27 UTC
Labels: Type: Bug, Package: @react-email/render

**Comment by leimantas** [comment] 2024-01-22 17:30
not working. still have same error:

```
[vite] Internal server error: Named export 'html' not found. The requested module 'js-beautify' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'js-beautify';
const { html } = pkg;
```

**Comment by jinsley8** [comment] 2024-01-22 17:33
> not working. still have same error:
> 
> ```
> [vite] Internal server error: Named export 'html' not found. The requested module 'js-beautify' is a CommonJS module, which may not support all module.exports as named exports.
> CommonJS modules can always be imported via the default export, for example using:
> 
> import pkg from 'js-beautify';
> const { html } = pkg;
> ```

- Update to `react-email` v2.0.0
- update other dependencies:
```
"@react-email/components": "0.0.14",
"@react-email/render": "0.0.12",
```
- delete `.next` and `.react-email` folders
- re-install npm packages - `npm install`, `bun install` or `yarn`

**Comment by leimantas** [comment] 2024-01-22 17:36
> > not working. still have same error:
> > ```
> > [vite] Internal server error: Named export 'html' not found. The requested module 'js-beautify' is a CommonJS module, which may not support all module.exports as named exports.
> > CommonJS modules can always be imported via the default export, for example using:
> > 
> > import pkg from 'js-beautify';
> > const { html } = pkg;
> > ```
> 
> * Update to `react-email` v2.0.0
> * update other dependencies:
> 
> ```
> "@react-email/components": "0.0.14",
> "@react-email/render": "0.0.12",
> ```
> 
>  * delete `.next` and `.react-email` folders
> * re-install npm packages - `npm install`, `bun install` or `yarn`

I'm using remix. And have cleared and reinstalled everything. Also have latest deps.

**Comment by leimantas** [comment] 2024-01-22 18:02
you can play with some small demo. check `app/root.tsx` file.

https://github.com/leimantas/resend-remix-demo

**Comment by leimantas** [comment] 2024-01-22 18:09
temp solution:
`package.json` 

```
 "resolutions": {
    "@react-email/render": "0.0.12"
  }
```

**Comment by jinsley8** [comment] 2024-01-22 18:29
> you can play with some small demo. check `app/root.tsx` file.
> 
> https://github.com/leimantas/resend-remix-demo
> 
> maybe because of this -> https://github.com/leimantas/resend-remix-demo/blob/83ab3b2d27b6c7cded05749d6aa756373692c112/pnpm-lock.yaml#L5468

@leimantas something is wrong with that repo.

I get this error: 
```
Cannot find module '@emotion/react/jsx-dev-runtime' imported from '/Users/jinsley8/Projects/Github Issues/resend-remix-demo/app/root.tsx'
```

If I do a fresh Remix install and add the react-email packages and resend it works fine.

**Comment by leimantas** [comment] 2024-01-22 18:32
https://www.npmjs.com/package/resend?activeTab=code

<img width="888" alt="image" src="https://github.com/resend/react-email/assets/46538777/c0a12696-0f59-4893-ab28-2157f97db664">

**Comment by leimantas** [comment] 2024-01-22 18:35
I use M1 mac with Node v20.11.0 and PNPM as package manager. 
Same problems not only on my laptop.  Resend has older `0.0.11` version.

And it does not work if you Install separate render  version `0.0.12` until you add `resolutions` in your package.json file.

**Comment by leimantas** [comment] 2024-01-22 19:01
But everything works on linux...

**Comment by gabrielmfern** [comment] 2024-01-22 19:11
@leimantas new version for tbe resend SDK that bumps render 3.1.0

**Comment by leimantas** [comment] 2024-01-22 19:15
> @leimantas new version for tbe resend SDK that bumps render 3.1.0

Thanks
