### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by raskyer** [resend/react-email#1234] opened 2024-01-23 20:23 UTC
### Describe the Bug

When I run `npm run tsc`

```
> tsc

node_modules/@react-email/code-block/dist/index.d.mts:3:19 - error TS7016: Could not find a declaration file for module 'prismjs'. '/node_modules/prismjs/prism.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/prismjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'prismjs';`

3 import Prism from 'prismjs';
                    ~~~~~~~~~

node_modules/@react-email/render/dist/index.d.mts:1:55 - error TS7016: Could not find a declaration file for module 'html-to-text'. '/node_modules/html-to-text/lib/html-to-text.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/html-to-text` if it exists or add a new declaration (.d.ts) file containing `declare module 'html-to-text';`

1 import { HtmlToTextOptions, SelectorDefinition } from 'html-to-text';
                                                        ~~~~~~~~~~~~~~

node_modules/@react-email/tailwind/dist/tailwind.d.ts:2:55 - error TS2307: Cannot find module 'tailwindcss' or its corresponding type declarations.

2 import type { Config as TailwindOriginalConfig } from "tailwindcss";
                                                        ~~~~~~~~~~~~~


Found 3 errors in 3 files.

Errors  Files
     1  node_modules/@react-email/code-block/dist/index.d.mts:3
     1  node_modules/@react-email/render/dist/index.d.mts:1
     1  node_modules/@react-email/tailwind/dist/tailwind.d.ts:2
```

### Link to the code that reproduces this issue

NA

### To Reproduce

- Install @react-email/render in typescript project
- Run tsc to check typescript types validity

### Expected Behavior

No error

### What's your node version? (if relevant)

^0.0.12

**Comment by gabrielmfern** [comment] 2024-01-24 12:34
Can you give a reproduction of this?

**Comment by hydrielax** [comment] 2024-01-31 09:32
I have the same problem here. To reproduce: 
- create a new react-email project
- create an email file in .tsx 
- run a typecheck on your project (`tsx`)
- the typecheck fails

After investigating, I think this is because some types from `@types/prismjs`, `@types/html-to-text`, and `@types/tailwindcss` are exported in the packages `@react-email/code-block`, `@react-email/render` and `@react-email/tailwind`, but the`@types/...` dependencies are defined in the `devDependencies` instead of the `dependencies` for each of these packages, so they are not available for type-checking on a custom project.

**Comment by gabrielmfern** [comment] 2024-02-04 14:33
Got a reproduction of something like this after messing around for a bit, do you all have `"skipLibCheck": false` or don't have it defined at all?

**Comment by hydrielax** [comment] 2024-02-26 11:17
`skipLibCheck` is not defined at all on my side (so defaulting to `true` I think)

**Comment by rossanodr** [comment] 2024-05-30 15:05
> ### Describe the Bug
> When I run `npm run tsc`
> 
> ```
> > tsc
> 
> node_modules/@react-email/code-block/dist/index.d.mts:3:19 - error TS7016: Could not find a declaration file for module 'prismjs'. '/node_modules/prismjs/prism.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/prismjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'prismjs';`
> 
> 3 import Prism from 'prismjs';
>                     ~~~~~~~~~
> 
> node_modules/@react-email/render/dist/index.d.mts:1:55 - error TS7016: Could not find a declaration file for module 'html-to-text'. '/node_modules/html-to-text/lib/html-to-text.mjs' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/html-to-text` if it exists or add a new declaration (.d.ts) file containing `declare module 'html-to-text';`
> 
> 1 import { HtmlToTextOptions, SelectorDefinition } from 'html-to-text';
>                                                         ~~~~~~~~~~~~~~
> 
> node_modules/@react-email/tailwind/dist/tailwind.d.ts:2:55 - error TS2307: Cannot find module 'tailwindcss' or its corresponding type declarations.
> 
> 2 import type { Config as TailwindOriginalConfig } from "tailwindcss";
>                                                         ~~~~~~~~~~~~~
> 
> 
> Found 3 errors in 3 files.
> 
> Errors  Files
>      1  node_modules/@react-email/code-block/dist/index.d.mts:3
>      1  node_modules/@react-email/render/dist/index.d.mts:1
>      1  node_modules/@react-email/tailwind/dist/tailwind.d.ts:2
> ```
> 
> ### Which package is affected (leave empty if unsure)
> _No response_
> 
> ### Link to the code that reproduces this issue
> NA
> 
> ### To Reproduce
> * Install @react-email/render in typescript project
> * Run tsc to check typescript types validity
> 
> ### Expected Behavior
> No error
> 
> ### What's your node version? (if relevant)
> ^0.0.12

did you manage to fix it? I'm facing the same issue

**Comment by renatoastra** [comment] 2024-06-23 15:09
Same problema here!

**Comment by gabrielmfern** [comment] 2024-07-25 20:08
Anyone having this issue, add `"skipLibCheck": true` to your ts config and it should be fine. Not an issue on React Email's side at all. Closing as not planned.

**Closed by gabrielmfern** 2024-07-25 20:08 UTC
Labels: Type: Bug, Package: @react-email/render, Resolution: Can't Reproduce, Package: @react-email/tailwind, Pacakge: @react-email/code-block

**Comment by alec202** [comment] 2024-10-08 18:29
I have it set to true and the issue still persists.

**Comment by pjs355** [comment] 2024-11-29 05:56
skipLibCheck did not work for me either.
