### ISSUE TITLE
[BUG] background image quoted url turned into html entities

### ISSUE THREAD

**Issue by haxxxton** [resend/react-email#442] opened 2023-02-04 08:42 UTC
Some older email clients only resepect background image urls if the url is quoted (ie. `background-image: url(./foo.jpg)` will not work, but `background-image: url("./foo.jpg")` will). When using quoted urls in provided styles, the output from `email export` replaces either double quotes `"` or single quotes `'` with html entities (`&quot;` and `&#x27;` respectively), breaking the inline style.

Steps to reproduce:
- create a template with an inline style that contains a style that includes backgroundImage with a quoted url. eg. `backgroundImage: "url('path/to/my/image.jpg')"`
- run `email export`
- note that style is replaced with `background-image: url(&#x27;path/to/my/image.jpg&#x27;)`

**Comment by heysujal** [comment] 2023-02-05 14:31
Can I work on this issue ?

**Comment by bukinoshita** [comment] 2023-02-06 15:32
Feel free to grab @heysujal

**Comment by heysujal** [comment] 2023-02-08 07:44
@bukinoshita When I make a react-email-stater using  `npx create-email@latest` then it keeps showing `Generating emails preview
` and keeps loading.
![image](https://user-images.githubusercontent.com/55016909/217465386-3e4d0de2-6fed-4dbf-91bf-17ba3996ab15.png)
![image](https://user-images.githubusercontent.com/55016909/217465510-b839900c-f59f-46f8-a2e2-cb2b5d41b453.png)
![image](https://user-images.githubusercontent.com/55016909/217465860-126c121b-a2e5-43e8-8e92-0463f7b6c2fa.png)
![image](https://user-images.githubusercontent.com/55016909/217465901-e1efe78c-77e8-490e-8f21-d9c1599bc41a.png)

**Comment by bastiaanv** [comment] 2023-02-10 11:22
@heysujal Can you try to place the `react-email-starter`-folder in a directory without spaces? Currently, the project is placed inside the `New folder (2)`, I am guessing that the whitespaces in the path is the problem

**Comment by heysujal** [comment] 2023-02-13 13:37
@bastiaanv thank you , I am able to run it my local system . Now, I am working to looking for a fix for the bug.

**Comment by haxxxton** [comment] 2023-02-14 01:55
@heysujal , i dont find that myself. when i do something with double quotes i end up with html entities like `&quot;` instead.

For example:
```jsx
// input
<div style={{ background: `no-repeat center bottom/contain url("${baseUrl}/foo.jpg") #000` } />
```

```html
<!-- output -->
<div style="background:no-repeat center bottom/contain url(&quot;https://example.com/foo.jpg&quot;) #000000"
```

This then breaks the rendered output such that no background image is displayed

**Comment by heysujal** [comment] 2023-02-14 05:16
I think the string template literal that you are using is causing the problem which I understand, it will be used when we have to use variables in a string. I only tested using simple quote outside url and double quote for enclosing the url which does not break the output.
Now I will try to reproduce bug using template literal the way you mentioned in above comment.

**Comment by bukinoshita** [comment] 2023-02-26 20:00
Would be great if anyone could help on this 🙏

**Comment by heysujal** [comment] 2023-02-26 20:37
> Would be great if anyone could help on this 🙏

I asked for help in discord and explained my issue as well. Can you have a look again at my message if I give you the link

**Comment by bukinoshita** [comment] 2023-02-26 20:42
> > Would be great if anyone could help on this 🙏
> 
> @bukinoshita I asked for help in discord and explained my issue as well. Can you have a look again at my message if I give you the link

Can you ping me there again, please? I probably missed. Or maybe we can add the case here as well so other people can related to the issue.

**Comment by haxxxton** [comment] 2023-02-26 23:21
my work around at the moment, is a second step to post process the built file output from react-email. let me know if you'd like a gist of it.. its not the most elegant.. but it works

**Comment by bukinoshita** [comment] 2023-02-27 00:07
> my work around at the moment, is a second typescript step to post-process the built file output from react-email. let me know if you'd like a gist of it.. its not the most elegant.. but it works

Would love to see so we can fix this, if you can share

**Comment by haxxxton** [comment] 2023-02-28 04:53
@bukinoshita  @heysujal  heres the fixer ts file. i have included how i run it, and my current package.json file. it basically just does regex replacements within the file

https://gist.github.com/haxxxton/1ae485b1896eed22d8f16808de696a02

**Comment by bukinoshita** [comment] 2023-03-01 05:33
@heysujal Can you take a look that and maybe this should be part of the `export` command?

**Comment by heysujal** [comment] 2023-03-01 12:42
@bukinoshita I am looking into it

**Comment by heysujal** [comment] 2023-03-02 15:28
@bukinoshita  I think we can use `unescape` function like I did [here](https://github.com/signalapp/Signal-Desktop/pull/5412).

**Comment by bukinoshita** [comment] 2023-03-03 17:06
> A similar bug was there in Signal App which I fixed.
> @bukinoshita I think we can use `unescape` function like I did [here](https://github.com/signalapp/Signal-Desktop/pull/5412).
> But the only difficulty I am facing here is when I make a change in `render` package then how can I see if my changes are working ?

Here's for reference https://github.com/resendlabs/react-email/issues/504. Let me know if that works

**Comment by heysujal** [comment] 2023-03-04 14:37
@bukinoshita that didn't work for me. We need clear instructions on how to build the project in the local system.

**Comment by bukinoshita** [comment] 2023-03-10 17:49
Yeah, you'll need to

1. make the changes in the `render` component
2. run `yarn build` to build the project
3. `yalc publish`
4. In a different project, run `yalc add @react-email/render`, check the package.json if it's referencing `yalc` package

**Comment by tdg5** [comment] 2023-06-07 17:13
I may be mistaken, but I think this is a `react-dom/server` issue, not a `react-email` issue. The relevant issue is this one I think: https://github.com/facebook/react/issues/13838.

Though I might ask, in what context is the `background-image` style broken? Is there a particular email client that has a problem with it? I tried exploring some and found that an element with an inline style like this seemed to work fine in most contexts:
```html
<div style="background-image:url(&#x27;https://www.iana.org/_img/2022/iana-logo-header.svg&#x27;)"></div>
```

**Comment by opiredev** [comment] 2024-05-02 16:36
@nabby27 created a $50.00 reward using [Opire](https://opire.dev) 
 <details><summary>How to earn this reward?</summary>

Since this project does not have Opire bot installed yet 😞 you need to go to [Opire](https://app.opire.dev) and claim the rewards through your programmer's dashboard once you have your PR ready 💪</details>

**Comment by aliraza556** [comment] 2024-09-04 17:25
@haxxxton [@nabby27](https://github.com/nabby27) issue is available?

**Comment by aliraza556** [comment] 2024-09-04 17:27
@nabby27, I see https://app.opire.dev/issues/01HWX2KCZZ0T410KPP75DT79EQ here that he is open to discussing the issue.

**Comment by nabby27** [comment] 2024-09-04 17:50
The bounty is available if the problem exists

**Comment by haxxxton** [comment] 2024-09-05 04:10
@aliraza556 go for it my dude. I havent looked at this since i added my "fixer" script to modify the output, but i would assume it still an issue as the issue @tdg5 identified is still open

**Comment by gabrielmfern** [comment] 2024-11-11 15:50
Closing in favor of #1767

**Closed by gabrielmfern** 2024-11-11 15:50 UTC
Labels: Type: Bug, Package: @react-email/render, Help needed
