### ISSUE TITLE
Buttons are not centered after the latest update

### ISSUE THREAD

**Issue by MartinXPN** [resend/react-email#1426] opened 2024-04-24 10:51 UTC
### Describe the Bug

Seems like after the latest update, the buttons that used to be centered in the emails are not centered anymore.
When running in `dev` mode, everything renders perfectly. Yet, when sending an actual email, the buttons are not centered anymore.

### Which package is affected (leave empty if unsure)

@react-email/button, @react-email/components, @react-email/container, @react-email/section

### Link to the code that reproduces this issue

https://github.com/MartinXPN/nextjs-firebase-mui-starter/tree/main/functions/emails

### To Reproduce

Here is the code to reproduce the issue:

```tsx
import {
    Body, Button, Container, Head, Hr, Html, Link, Preview, Section, Text,
} from '@react-email/components';
import React from 'react';


export const StreakReminderEmail = ({userId, streak = 0}: {
    userId: string,
    streak: number,
}) => (
    <Html>
        <Head/>
        <Preview>Consistency is Key. Keep your streak going!</Preview>
        <Body style={{
            // eslint-disable-next-line max-len
            fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif',
            lineHeight: '24px',
            // backgroundColor: '#ffffff',
        }}>
            <Container style={{margin: 'auto'}}>
                <Text style={{
                    fontSize: '24px', fontFamily: '"Montserrat",sans-serif', fontWeight: 'bold',
                    textAlign: 'center', whiteSpace: 'pre-line', paddingTop: '32px',
                }}>
                    You are on a {streak} day streak 🔥
                </Text>
                <Text style={{fontSize: '16px', textAlign: 'center'}}>
                    Consistency is key!
                    Keep the streak going by learning something new today!
                </Text>

                <Section style={{display: 'flex', justifyContent: 'center', width: '100%'}}>
                    <Button style={button} href="https://profound.academy">
                        Continue Learning
                    </Button>
                </Section>

                
            </Container>
        </Body>
    </Html>
);

export default StreakReminderEmail;


const button = {
    backgroundColor: '#fa541c',
    borderRadius: '50px',
    color: '#fff',
    fontSize: '16px',
    fontWeight: 'bold',
    textDecoration: 'none',
    textAlign: 'center' as const,
    maxWidth: '100%',
    paddingLeft: '24px',
    paddingRight: '24px',
    paddingTop: '12px',
    paddingBottom: '12px',
};
```

### Expected Behavior

The button should be centered. It used to be centered using the previous version. It's shifted to the left instead now (see the screenshot below)

<img width="541" alt="Screenshot 2024-04-24 at 2 50 03 PM" src="https://github.com/resend/react-email/assets/16335716/8b008bdf-a571-418a-b133-15b5d3515ed4">

### What's your node version? (if relevant)

20

**Comment by gabrielmfern** [comment] 2024-04-24 12:24
What email client are you testing this on?

This might be because `justify-content` does not have the best support, not sure why this would work on an older version of ours as this isn't really very [well-supported](https://www.caniemail.com/features/css-justify-content/).

**Comment by MartinXPN** [comment] 2024-04-24 12:27
Gmail. It used to work just fine. Doesn't work anymore and I'm not sure why.

**Comment by gabrielmfern** [comment] 2024-04-24 12:34
What version did it work on?

**Comment by MartinXPN** [comment] 2024-04-24 12:36
Was fine with these:
```
    "@react-email/components": "^0.0.12",
    "react-email": "^1.10.0"
```

**Comment by MartinXPN** [comment] 2024-04-24 13:42
Interesting... it used to work fine.
Can you provide a bit more details on what would be the right way to center the button with the latest version?

**Comment by gabrielmfern** [comment] 2024-04-24 15:20
I don't think looking at a screenshot of what happened back then is going to be reliable to understand if the issue is on our side, since Gmail might have updated things back and forth on this. Not sure.

> Can you provide a bit more details on what would be the right way to center the button with the latest version?

Something like this should work:

```jsx
<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td align="center">
		    <Button style={button} href="https://profound.academy/">
		        Continue Learning
		    </Button>
		</td>
	</tr>
</table>
```

**Comment by MartinXPN** [comment] 2024-04-25 06:36
Thanks for the provided code. This worked:
```tsx
<table width="100%" border={0} cellSpacing={0} cellPadding={0}>
    <tbody>
        <tr>
            <td align="center">
                <Button style={{...button}} href="https://profound.academy">
                    Continue Learning
                </Button>
            </td>
        </tr>
    </tbody>
</table>
```

Seems like most `react-email` examples (like [this one](https://demo.react.email/preview/notifications/github-access-token?view=desktop)) use way simpler methods to center buttons. Do you think there is a better/simpler way of reliably centering a div in emails?

P.S. I tried to downgrade the libraries and the button is not centered anymore. So, it seems like there has been some update to how Gmail renders things.

**Comment by gabrielmfern** [comment] 2024-04-25 17:34
Good to know that it's a Gmail issue.

Yeah, those examples align it with a `text-align: center`, it should work in your case as well if you do it with that. But I don't remember exactly if that works because `Section` uses a table under the hood, or if it's because Button is an `<a>`. It might be the former.

Going to close the issue as not planned since this is a Gmail issue.

**Closed by gabrielmfern** 2024-04-25 17:34 UTC
Labels: Type: Bug, Package: @react-email/button

**Comment by MartinXPN** [comment] 2024-04-25 19:37
Sounds good, thank you so much for your help!
