### ISSUE TITLE
Heading component not getting rendered in "react-email": "2.1.1" and "@react-email/components": "0.0.16",

### ISSUE THREAD

**Issue by desmigor** [resend/react-email#1410] opened 2024-04-12 13:06 UTC
### Describe the Bug

I was using version `"react-email": "2.1.1"` and `"@react-email/components": "0.0.16"` and the Heading component wasn't getting rendered.

When I switched back to `"react-email": "2.0.0"` and `"@react-email/components": "0.0.14"`, now the Heading component is getting displayed. Can you check what's wrong with the new updates. Thanks!

### Which package is affected (leave empty if unsure)

@react-email/heading

### Link to the code that reproduces this issue

Private repo

### To Reproduce

Use `"react-email": "2.1.1"` and `"@react-email/components": "0.0.16"` and add <Heading>Hello world</Heading> in the email template

### Expected Behavior

The heading won't be rendered/displayed.

### What's your node version? (if relevant)

v20.6.0

**Comment by gabrielmfern** [comment] 2024-04-12 13:11
This has already been fixed under canary for  `@react-email/components@0.0.17-canary.1`.

Closing as not planned due to it being a duplicate of #1391

**Closed by gabrielmfern** 2024-04-12 13:11 UTC
Labels: Type: Bug
