### ISSUE TITLE
npm run dev not opening port

### ISSUE THREAD

**Issue by sysmat** [resend/react-email#747] opened 2023-07-05 09:29 UTC
### Describe the Bug

npm run dev -> nothing happend

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://stackblitz.com/edit/stackblitz-starters-tcqzzt?file=react-email-starter%2Freadme.md

### To Reproduce

- npx create-email@latest
- ncu -u
- npm i
- npm run dev -> nothing happend

### Expected Behavior

to start dev server on http://localhost:3001 as in readme documentation

### What's your node version? (if relevant)

Node: 18.16.0

**Comment by bukinoshita** [comment] 2023-07-06 17:17
@sysmat Can you share more information? Is this on Mac? Windows? Linux?

Here's the same steps

https://github.com/resendlabs/react-email/assets/6929565/e94f4d1d-9b59-4449-8c66-cc6b11646f5c

**Comment by sysmat** [comment] 2023-07-07 07:24
@bukinoshita on windows power shell

![react_email](https://github.com/resendlabs/react-email/assets/69830/c1a435f1-d875-4ec7-aa0c-dbfd5d3fcddf)

**Comment by Rivoks** [comment] 2023-07-09 11:37
Hello me too, when launching npm run dev it is starting and then closing immediately the process.

**Comment by mortocks** [comment] 2023-07-11 06:47
+1 

node 18.16.0
pnpm 8.6.3

**Comment by bukinoshita** [comment] 2023-07-11 15:41
All windows? Or anyone having this issue on Mac?

**Comment by mezg0** [comment] 2023-07-12 11:29
Yeah same issue for me on Mac

**Comment by mortocks** [comment] 2023-07-12 14:28
Today (24 hours after my original post) it suddenly started working (no changes to the code base or system restarts. The first thing it did was download a bunch of dependancies.

I'm wondering if perhaps a host for one of these dependancies was down and there's no error handing in the startup process? 🤷‍♂️ 

Just a new data point

**Comment by bighoho123** [comment] 2023-07-13 07:36
Same here.
Mac M1 `react-email@1.9.4`

Running `email` script exits immediately (without error)

<img width="638" alt="Cursor_and_Hyper" src="https://github.com/resendlabs/react-email/assets/7004799/70e35061-e37b-4bcf-a369-cc17789e5aae">

**Comment by bighoho123** [comment] 2023-07-13 11:17
`npm uninstall react-email`
then
`npm install react-email -D -E` fixed my issue

**Comment by zedo-san** [comment] 2023-07-14 02:21
I tried installing the previous version `"react-email": "1.9.0"` and it works fine for me. I'm using a windows machine. Here's my full `package.json` file
```
{
  "name": "react-email-p1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "email dev"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@react-email/button": "0.0.7",
    "@react-email/components": "0.0.4",
    "@react-email/container": "0.0.8",
    "@react-email/html": "0.0.4",
    "@react-email/tailwind": "0.0.7",
    "react-email": "1.9.0"
  }
}

```

**Comment by stbensonimoh** [comment] 2023-07-14 20:41
I had the same issue. I had to use `npx react-email dev` instead of `npm run dev` before it worked for me.

**Comment by Rivoks** [comment] 2023-07-22 14:35
With the latest version `1.9.4` i got this error when I run the `npm dev`:
```bash
> email dev --port 8888 --dir src/emails

(node:30994) [DEP0164] DeprecationWarning: Implicit coercion to integer for exit code is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by EavOutDom** [comment] 2023-09-23 04:44
I also have the same issue with windows

**Comment by Aleksandern** [comment] 2023-11-06 02:40
`react-email` downloads the client code on the start (about 24 MB) so make sure you have a good internet connection or just wait for a while.
That was my issue.

**Comment by gabrielmfern** [comment] 2024-01-27 11:53
This should not happen the same as of `react-email@2.0.0` and should now be fixed.

Check the [changelog](https://react.email/docs/changelog#jan-19-2024) and our [blog post](https://resend.com/blog/react-email-2) for more info on this.

If anyone is still experiencing this with 2.0.0 let me know and I'll reopen this issue.

**Closed by gabrielmfern** 2024-01-27 11:53 UTC
Labels: Type: Bug, Package: react-email

**Comment by Yashhh08** [comment] 2024-02-09 07:34
$ npm run email

> emails@0.1.0 email
> email dev

    React Email 2.0.0
    Running preview at:          http://localhost:3000

  ⠙ Getting react-email preview server ready...
Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
    at findPagesDir (D:\Yash Yerunkar\Email Templates\emails\node_modules\react-email\node_modules\next\dist\lib\find-pages-dir.js:42:15)
    at initialize (D:\Yash Yerunkar\Email Templates\emails\node_modules\react-email\node_modules\next\dist\server\lib\router-server.js:71:69)
    at async NextCustomServer.prepare (D:\Yash Yerunkar\Email Templates\emails\node_modules\react-email\node_modules\next\dist\server\next.js:240:28)

shutting down dev server


Getting above issue

**Comment by codeScourge** [comment] 2024-04-21 07:04
> @codeScourge Could you provide a reproduction for this? Seems to be another issue other than the one here.

Hi, thank you for helping. Here is the reproduction: https://github.com/codeScourge/react-email
There are some more details in the ReadME

**Comment by gabrielmfern** [comment] 2024-04-23 14:44
@codeScourge I think I've figured it out. When running on WSL you might have not installed Node at all, in that case, it seems like it fails the same you mentioned. It also fails the same way when running with `bun --bun dev` while having Node installed. So that seems like what is happening. 

Could you open an issue with your reproduction and this documented as well? Some error might be happening due to some incompatibility with bun, and I'll try taking a look right now.

**Comment by codeScourge** [comment] 2024-04-25 06:05
> @codeScourge I think I've figured it out. When running on WSL you might have not installed Node at all, in that case, it seems like it fails the same you mentioned. It also fails the same way when running with `bun --bun dev` while having Node installed. So it seems like bun falls back to running with its runtime if Node isn't installed, so basically it runs `bun --bun dev`. Haven't checked on their code and I couldn't find anything related to this on their docs.
> 
> Could you open an issue with your reproduction and this documented as well? Some error might be happening due to some incompatibility with bun, and I'll try taking a look right now. Just want to move our conversation there instead.

Sure, it is up at https://github.com/resend/react-email/issues/1429
