### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by ktlyee** [resend/react-email#1130] opened 2024-01-10 03:54 UTC
### Describe the Bug

I created project by manual setup followed this link https://react.email/docs/getting-started/manual-setup. I got this error when I tried to run `yarn dev` first time. It said
```
const stripAnsi = require('strip-ansi');
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/kty/Documents/email-template-generator/node_modules/strip-ansi/index.js from /Users/kty/Documents/email-template-generator/node_modules/ora/index.js not supported.
Instead change the require of /Users/kty/Documents/email-template-generator/node_modules/strip-ansi/index.js in /Users/kty/Documents/email-template-generator/node_modules/ora/index.js to a dynamic import() which is available in all CommonJS modules.
at Object.<anonymous> (/Users/kty/Documents/email-template-generator/node_modules/ora/index.js:7:19) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.10.0
```

### Link to the code that reproduces this issue

https://github.com/resendlabs/react-email

### To Reproduce

I had 2 ways that resolved this error.
1. I removed `yarn.lock` file (outside `.react-email` folder) and run `yarn` and `yarn dev` again.
2. Downgrade version of `strip-ansi` to be `v6.0.0` in package.json (outside `.react-email` folder).

### Expected Behavior

When run `yarn` and `yarn dev`, this error shouldn't happen.

### What's your node version? (if relevant)

v20.10.0

**Comment by trungne** [comment] 2024-01-10 05:34
I also have this problem on node v21.4.0. Have to do `yarn install --no-lockfile` to bypass the problem but I don't think it's a good solution as it can cause unexpected installation of packages.

**Comment by NetSpud** [comment] 2024-01-10 20:42
I had this issue too, only this time I was using the `yarn create email` command instead.

**Comment by gabrielmfern** [comment] 2024-01-12 14:38
This seems to be caused in part because `strip-ansi` 7.0.0 is pure ESM, do you guys have any idea what we use that depends on strip-ansi?

**Comment by jinsley8** [comment] 2024-01-17 06:17
This is an issue with yarn v1 not compatible with eslint: [Eslint #17215](https://github.com/eslint/eslint/discussions/17215)

**Comment by gabrielmfern** [comment] 2024-01-17 07:19
Closing as a duplicate of #1075

**Closed by gabrielmfern** 2024-01-17 07:19 UTC
Labels: Type: Bug, Package: @react-email/react-email
