### ISSUE TITLE
Tooltip content text is invisible

### ISSUE THREAD

**Issue by Fadingvision** [resend/react-email#1326] opened 2024-02-23 09:19 UTC
### Describe the Bug

![image](https://github.com/resend/react-email/assets/15011394/0ede4037-81b5-43fb-b0aa-7126e4db12ca)

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://demo.react.email/preview/notifications/github-access-token?view=source

### To Reproduce

https://demo.react.email/preview/notifications/github-access-token?view=source

### Expected Behavior

Tooltip content text is visible

**Comment by gabrielmfern** [comment] 2024-02-23 13:27
Seems ok for me, the tooltip seems to appear fine
![image](https://github.com/resend/react-email/assets/88866334/356ba6ab-4e21-4367-8f65-36e423300007)

**Comment by Fadingvision** [comment] 2024-02-26 07:55
@gabrielmfern  looked into some details, this bug looks like it is related to os theme, further information:

## os info
windows 10
chrome version(121.0.6167.189)


### windows light theme: 

![image](https://github.com/resend/react-email/assets/15011394/bb8d7c21-9e86-4a59-880b-0a8da701f99d)


### windows dark theme(which looks fine): 

![image](https://github.com/resend/react-email/assets/15011394/a5dababe-a45c-4336-a606-49a79471bf2a)


Looks like the text color should be set to white anyways, hope it helps.

**Comment by devharipragaz007** [comment] 2024-03-04 23:33
is the bug still exists? Shall I give it a try?

**Comment by gabrielmfern** [comment] 2024-03-11 11:10
> is the bug still exists? Shall I give it a try?

Yup it's still there.
PR's are welcome! Would love to review yours if you do make one.
You also don't have to ask permission to open one either. :)

**Comment by ffiona** [comment] 2024-03-11 15:53
On Mac OS is the same, depends on the system theme.

![Screenshot 2024-03-11 at 16 50 35](https://github.com/resend/react-email/assets/1404938/7ea2104b-05f1-45b7-a2e9-056461a87e80)

**Comment by devharipragaz007** [comment] 2024-03-12 01:35
> > is the bug still exists? Shall I give it a try?
> 
> Yup it's still there. PR's are welcome! Would love to review yours if you do make one. You also don't have to ask permission to open one either. :)

Please assign this to me.

**Comment by kaustabhws** [comment] 2024-04-27 15:43
![Screenshot 2024-04-27 210800](https://github.com/resend/react-email/assets/118001401/67ef3620-1ae7-4477-ba3a-eae43cbe7c60)


Hello, it's my first time commenting on a issue. but I'd like to add something. I think the issue in here
`<TooltipPrimitive.Content
      {...props}
      className={cn(
        'bg-black border border-slate-6 z-20 px-3 py-2 rounded-md text-xs',
        `${inter.variable} font-sans`,
      )}
      ref={forwardedRef}
      sideOffset={sideOffset}
    >
      {children}
    </TooltipPrimitive.Content>`

instead of giving `bg-black` we can set the color based on the theme. I haven't explored the entire code so I'm not sure what is being used for themes, but maybe use external package and conditionally change the bg color, for eg `dark:bg-black` for dark mode and default `bg-white`. Forgive me if I'm commenting anything wrong

**Comment by ranafaraznaru** [comment] 2024-07-24 22:59
Hey, I've checked and the issue is still present, can you please assign it to me?

**Comment by ranafaraznaru** [comment] 2024-07-24 23:01
@gabrielmfern Hey, I've checked and the issue is still present, can you please assign it to me?

**Comment by gabrielmfern** [comment] 2024-10-31 14:58
This seems to be fixed since `react-email@3.0.0`!

**Closed by gabrielmfern** 2024-10-31 14:58 UTC
Labels: Type: Bug, Package: react-email, Type: Good First Issue
