### ISSUE TITLE
`email dev` command always fails on Windows

### ISSUE THREAD

**Issue by lazlothemonkey** [resend/react-email#1225] opened 2024-01-23 00:47 UTC
### Describe the Bug

I am using the latest version of React Email (2.0.0) and Next.js (13.5.4)

When I run "email dev" I get the following error:

```React Email 2.0.0
    Running preview at:          http://localhost:3000

  ⠙ Getting react-email preview server ready...
Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
```

But I clearly do have an app directory... what's going on? 
Also don't really want to upgrade to Next 14 atm, because it'll break some things.

### Link to the code that reproduces this issue

https://github.com/lazlothemonkey/reactemail_test

### To Reproduce

Just run "npm run email"

### Expected Behavior

I expect to run the email preview server

**Comment by LavransBjerkestrand** [comment] 2024-01-23 02:13
Your repo is not public

**Comment by kapilrc** [comment] 2024-01-23 07:56
Switch to node -v 16.17.0 and it will work. 
The above issue is reproducable in node -v 18.17.0 or >18

**Comment by lazlothemonkey** [comment] 2024-01-23 08:10
@LavransBjerkestrand I updated my post with a minimal public repo, where you can recreate the issue

@kapilrc I also fixed it by downgrading to `"react-email": "^1.10.1",`  AND `"@react-email/components": "^0.0.7",`

**Comment by gabrielmfern** [comment] 2024-01-23 08:23
This was an issue introduced with `2.0.0`, so just downgrading `react-email` would work but also not using Windows temporarily will fix this. 

I don't recommend using the older versions though, and using the above patch would be much better here as it is much more stable and better for use.

**Comment by kapilrc** [comment] 2024-01-23 11:59
Hi @gabrielmfern , Tried multiple ways on window, with the above repo as well seeing below error
Windows issue.

```
> email dev -p 3030

RequestError [HttpError]: fetch failed
    at G:\projects\next13-ticketing-app\node_modules\@octokit\request\dist-node\index.js:146:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/resendlabs/react-email/tarball/v0.0.15',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.7 octokit-core.js/4.2.4 Node.js/18.17.0 (win32; x64)'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```
I see an open PR raised by you. Hope to see it merged soon.

Thanks,

**Comment by gabrielmfern** [comment] 2024-01-23 12:27
@kapilrc Seems like you're using the `1.x.x` version for the CLI. If you use `react-email@2.0.0` you won't have that issue anymore.

See https://resend.com/blog/react-email-2

**Comment by kapilrc** [comment] 2024-01-23 13:18
Hi @gabrielmfern , I was point on the same issue.. not opening the preview email.. even though using react-email @2.0.0 there is another issue I see
```
> email dev -p 3030

    React Email 2.0.0
    Running preview at:          http://localhost:3030

  ⠙ Getting react-email preview server ready...
Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
    at findPagesDir (G:\projects\next13-ticketing-app\node_modules\react-email\node_modules\next\dist\lib\find-pages-dir.js:42:15)
    at initialize (G:\projects\next13-ticketing-app\node_modules\react-email\node_modules\next\dist\server\lib\router-server.js:71:69)
    at async NextCustomServer.prepare (G:\projects\next13-ticketing-app\node_modules\react-email\node_modules\next\dist\server\next.js:240:28)

shutting down dev server
```

Tried with `next: 14.1.0` and `next 13.5.4`
package.json

```
{
  ...
  "dependencies": {
  "@react-email/components": "^0.0.14",
  "react-email": "^2.0.0",
  "resend": "^3.1.0",
}
```

Thanks,

**Comment by gabrielmfern** [comment] 2024-01-23 13:27
> ```
> email dev -p 3030
>
>    React Email 2.0.0
>    Running preview at:          http://localhost:3030
>
>  ⠙ Getting react-email preview server ready...
> Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
>     at findPagesDir (G:\projects\next13-ticketing-app\node_modules\react-email\node_modules\next\dist\lib\find-pages-dir.js:42:15)
>    at initialize (G:\projects\next13-ticketing-app\node_modules\react-email\node_modules\next\dist\server\lib\router-server.js:71:69)
>    at async NextCustomServer.prepare (G:\projects\next13-ticketing-app\node_modules\react-email\node_modules\next\dist\server\next.js:240:28)
>
> shutting down dev server
> ```
@kapilrc The above issue you mention is the one that the [patch](https://github.com/resend/react-email/issues/1225#issuecomment-1905529562) and the PR #1216 fixes.

About the other issue you saw with the `1.x.x` is something that used to happen here and there, so if you try enough I think it might not be an error.

**Comment by kapilrc** [comment] 2024-01-23 13:37
Yes this has fixed. Many thanks :)

**Comment by lazlothemonkey** [comment] 2024-01-23 17:01
> ```diff
> while (newPath.endsWith(pathSeparator)) {
> ```

Thanks the patch fixes it.

**Comment by lazlothemonkey** [comment] 2024-01-23 17:02
> There's already a PR open for this issue, #1216, and here's a patch as a quick workaround for now:
> 
> ```diff
> diff --git a/cli/index.js b/cli/index.js
> index 15c8732e1bcf274d9d99ea8de55ed0e959fb5d16..69ef51c7eb11a02b0e2e5c95e0c95c92d5175735 100644
> --- a/cli/index.js
> +++ b/cli/index.js
> @@ -508,7 +508,7 @@ var safeAsyncServerListen = function(server, port) {
>          });
>      });
>  };
> -var isRunningBuilt = __filename.endsWith("cli/index.js");
> +var isRunningBuilt = __filename.endsWith(import_node_path3.default.join("cli", "index.js"));
>  var cliPacakgeLocation = isRunningBuilt ? import_node_path3.default.resolve(__dirname, "..") : import_node_path3.default.resolve(__dirname, "../../../..");
>  var startDevServer = function() {
>      var _ref = _async_to_generator(function(emailsDirRelativePath, staticBaseDirRelativePath, port) {
> diff --git a/src/utils/emails-directory-absolute-path.ts b/src/utils/emails-directory-absolute-path.ts
> index 256fd506049dbd7d83c188d3785c535633482ee5..ccbcb541710a16ad84ba4fcf6312500db81097b2 100644
> --- a/src/utils/emails-directory-absolute-path.ts
> +++ b/src/utils/emails-directory-absolute-path.ts
> @@ -14,15 +14,15 @@ export const pathSeparator = process.env.NEXT_PUBLIC_OS_PATH_SEPARATOR! as
>  const normalizePath = (path: string) => {
>    let newPath = path;
>  
> -  while (newPath.startsWith('./')) {
> +  while (newPath.startsWith(`.${pathSeparator}`)) {
>      newPath = newPath.slice(2);
>    }
>  
> -  while (newPath.startsWith('/')) {
> +  while (newPath.startsWith(pathSeparator)) {
>      newPath = newPath.slice(1);
>    }
>  
> -  while (newPath.endsWith('/')) {
> +  while (newPath.endsWith(pathSeparator)) {
>      newPath = newPath.slice(0, -1);
>    }
> ```

thanks the patch fixes it for me.

**Comment by s1xp4c** [comment] 2024-01-28 21:19
> There's already a PR open for this issue, #1216, and here's a patch as a quick workaround for now:
> 
> ```diff
> diff --git a/cli/index.js b/cli/index.js
> index 15c8732e1bcf274d9d99ea8de55ed0e959fb5d16..69ef51c7eb11a02b0e2e5c95e0c95c92d5175735 100644
> --- a/cli/index.js
> +++ b/cli/index.js
> @@ -508,7 +508,7 @@ var safeAsyncServerListen = function(server, port) {
>          });
>      });
>  };
> -var isRunningBuilt = __filename.endsWith("cli/index.js");
> +var isRunningBuilt = __filename.endsWith(import_node_path3.default.join("cli", "index.js"));
>  var cliPacakgeLocation = isRunningBuilt ? import_node_path3.default.resolve(__dirname, "..") : import_node_path3.default.resolve(__dirname, "../../../..");
>  var startDevServer = function() {
>      var _ref = _async_to_generator(function(emailsDirRelativePath, staticBaseDirRelativePath, port) {
> diff --git a/src/utils/emails-directory-absolute-path.ts b/src/utils/emails-directory-absolute-path.ts
> index 256fd506049dbd7d83c188d3785c535633482ee5..ccbcb541710a16ad84ba4fcf6312500db81097b2 100644
> --- a/src/utils/emails-directory-absolute-path.ts
> +++ b/src/utils/emails-directory-absolute-path.ts
> @@ -14,15 +14,15 @@ export const pathSeparator = process.env.NEXT_PUBLIC_OS_PATH_SEPARATOR! as
>  const normalizePath = (path: string) => {
>    let newPath = path;
>  
> -  while (newPath.startsWith('./')) {
> +  while (newPath.startsWith(`.${pathSeparator}`)) {
>      newPath = newPath.slice(2);
>    }
>  
> -  while (newPath.startsWith('/')) {
> +  while (newPath.startsWith(pathSeparator)) {
>      newPath = newPath.slice(1);
>    }
>  
> -  while (newPath.endsWith('/')) {
> +  while (newPath.endsWith(pathSeparator)) {
>      newPath = newPath.slice(0, -1);
>    }
> ```

This fixed it for me as well . .. Thanx a lot <3 

    "next": "13.4.3",
    "react": "^18.2.0",
     "react-email": "2.0.0",
     "@react-email/components": "0.0.14",

**Comment by HQ92** [comment] 2024-01-29 12:39
I've tried the fix out, it fixes the issue with the dev server not launching but it does not work with subdirectories in the emails folder if you want to organise emails inside their own directories.

![image](https://github.com/resend/react-email/assets/9061823/df20542a-6a33-44b7-acbb-284ef68e5078)

**Comment by gabrielmfern** [comment] 2024-01-29 14:52
@HQ92 You might've applied the patch wrong here because, IIRC, the second portion of the patch fixes that issue as well you're having

**Comment by gabrielmfern** [comment] 2024-01-29 14:53
If anyone wants some help applying the patch I've made a much-needed guide for applying any patch I send:

**Comment by HQ92** [comment] 2024-01-29 16:23
> @HQ92 You might've applied the patch wrong here because, IIRC, the second portion of the patch fixes that issue as well you're having

My patch file with patch-package is as follows:

```patch
// react-email+2.0.0.patch

diff --git a/node_modules/react-email/cli/index.js b/node_modules/react-email/cli/index.js
index 15c8732..69ef51c 100644
--- a/node_modules/react-email/cli/index.js
+++ b/node_modules/react-email/cli/index.js
@@ -508,7 +508,7 @@ var safeAsyncServerListen = function(server, port) {
         });
     });
 };
-var isRunningBuilt = __filename.endsWith("cli/index.js");
+var isRunningBuilt = __filename.endsWith(import_node_path3.default.join("cli", "index.js"));
 var cliPacakgeLocation = isRunningBuilt ? import_node_path3.default.resolve(__dirname, "..") : import_node_path3.default.resolve(__dirname, "../../../..");
 var startDevServer = function() {
     var _ref = _async_to_generator(function(emailsDirRelativePath, staticBaseDirRelativePath, port) {
diff --git a/node_modules/react-email/src/utils/emails-directory-absolute-path.ts b/node_modules/react-email/src/utils/emails-directory-absolute-path.ts
index 256fd50..ccbcb54 100644
--- a/node_modules/react-email/src/utils/emails-directory-absolute-path.ts
+++ b/node_modules/react-email/src/utils/emails-directory-absolute-path.ts
@@ -14,15 +14,15 @@ export const pathSeparator = process.env.NEXT_PUBLIC_OS_PATH_SEPARATOR! as
 const normalizePath = (path: string) => {
   let newPath = path;

-  while (newPath.startsWith('./')) {
+  while (newPath.startsWith(`.${pathSeparator}`)) {
     newPath = newPath.slice(2);
   }

-  while (newPath.startsWith('/')) {
+  while (newPath.startsWith(pathSeparator)) {
     newPath = newPath.slice(1);
   }

-  while (newPath.endsWith('/')) {
+  while (newPath.endsWith(pathSeparator)) {
     newPath = newPath.slice(0, -1);
   }
```

I have verified that the raw files in node_modules are correctly modified and should match your patch.

**Comment by Hainesy** [comment] 2024-01-31 20:35
Any update on fixing this?

This is affecting MacOS too. I'm in a mono-repo, not sure if that makes any difference.

**Comment by HQ92** [comment] 2024-01-31 21:06
I'm also using react-email inside a turborepo monorepo under packages/transactional as per the docs.

**Comment by gabrielmfern** [comment] 2024-01-31 21:09
@Hainesy 
> This is affecting MacOS too. I'm in a mono-repo, not sure if that makes any difference.

Interesting, it shouldn't happen on Mac as it uses `/` as a path separator this might be another issue, could you make a repro?

**Comment by Hainesy** [comment] 2024-02-01 10:57
You're right, it does seem to be a different issue, the patch doesn't work for me. 

The setup we have is a pnpm monorepo. I am unable to create repro right now due to time constraints. I think I'll just have to downgrade to v1 for now.

**Comment by bfourgeaud** [comment] 2024-02-02 16:10
Thanks for the patch, it worked !

**Comment by tacheometry** [comment] 2024-02-04 18:38
Running in WSL works for me as a temporary fix.

**Comment by TomQuast** [comment] 2024-02-05 12:45
Any progress on this :)?

**Comment by gabrielmfern** [comment] 2024-02-05 17:12
@TomQuast We have #1216 but if you are having this on Mac or somewhere #1216 doesn't fix it

**Comment by gabrielmfern** [comment] 2024-02-07 12:08
@NickHoFlare You're experiencing #1235

**Closed** 2024-02-07 12:24 UTC
Labels: Type: Bug, Package: react-email, OS: Windows

**Comment by gabrielmfern** [comment] 2024-02-09 14:17
This has been fixed under `react-email@2.1.0-canary.1`, stable release soon!

**Comment by MS-BOV** [comment] 2024-02-21 11:23
Hi, I am running react-email@2.1.0-canary.1 on Windows 10, node 20.11.0, and when I run the dev everything works fine until I try and view a file in a subdirectory of the emails folder and then I get the same build error as mentioned before. When checking the node-modules files, it looks like the fixes mentioned in the patch are already applied.  
![image](https://github.com/resend/react-email/assets/87976514/b1b428b0-5d09-4b79-86af-aa66c4a4f128)

![image](https://github.com/resend/react-email/assets/87976514/6a029ba2-a3f3-42eb-a165-a96bd86647de)

**Comment by gabrielmfern** [comment] 2024-03-18 15:22
@bennyburrito So sorry for the late reply here, but seems like the latest canary release has this fixed.

See issue #1354 and release notes https://github.com/resend/react-email/releases/tag/react-email%402.1.1-canary.1.

**Comment by johanmic** [comment] 2024-03-21 14:39
> @bennyburrito So sorry for the late reply here, but seems like the latest canary release has this fixed.
> 
> See issue #1354 and release notes https://github.com/resend/react-email/releases/tag/react-email%402.1.1-canary.1.

this fixed it for me!

nvm node v18.17.1

**Comment by rumfiske** [comment] 2024-04-28 10:51
Version   "react-email": "^2.1.1", and   "@react-email/components": "^0.0.16", works with nextjs app router. Node v20.12.2
